### ISSUE TITLE
About label of Text Recognition

### ISSUE THREAD

**Issue by ThaiLe189** [rickyHong/STN-OCR-repl#1]
Hello @rickyHong 
I'm working on the text recognition of this code and I don't know how to label it
Can you show me a example of label of text recognition ?
Thank you!

**Comment by rickyHong** [comment]
Please note that we refined our approach and released new source code. 
You can find the code [here](https://github.com/Bartzi/see)

**Comment by ThaiLe189** [comment]
Yeah I have checked it already but my mentor want me to use this code so can you help me ? 
Thank you for reply!
